import type { ThemeColorOption, FontFamilyOption, CustomizerSettings } from '../types/themeCustomizer.types';

export const THEME_COLORS: ThemeColorOption[] = [
  {
    id: 'violet',
    name: 'Classic Violet',
    primary: '#7c3aed',
    hover: '#6d28d9',
    active: '#5b21b6',
    lightBg: 'rgba(124, 58, 237, 0.12)',
    ring: '#a78bfa',
    badgeClass: 'bg-violet-600',
  },
  {
    id: 'blue',
    name: 'Ocean Blue',
    primary: '#2563eb',
    hover: '#1d4ed8',
    active: '#1e40af',
    lightBg: 'rgba(37, 99, 235, 0.12)',
    ring: '#60a5fa',
    badgeClass: 'bg-blue-600',
  },
  {
    id: 'indigo',
    name: 'Royal Indigo',
    primary: '#4f46e5',
    hover: '#4338ca',
    active: '#3730a3',
    lightBg: 'rgba(79, 70, 229, 0.12)',
    ring: '#818cf8',
    badgeClass: 'bg-indigo-600',
  },
  {
    id: 'emerald',
    name: 'Emerald Green',
    primary: '#059669',
    hover: '#047857',
    active: '#065f46',
    lightBg: 'rgba(5, 150, 105, 0.12)',
    ring: '#34d399',
    badgeClass: 'bg-emerald-600',
  },
  {
    id: 'rose',
    name: 'Crimson Rose',
    primary: '#e11d48',
    hover: '#be123c',
    active: '#9f1239',
    lightBg: 'rgba(225, 29, 72, 0.12)',
    ring: '#fb7185',
    badgeClass: 'bg-rose-600',
  },
  {
    id: 'amber',
    name: 'Sunset Amber',
    primary: '#d97706',
    hover: '#b45309',
    active: '#92400e',
    lightBg: 'rgba(217, 119, 6, 0.12)',
    ring: '#fbbf24',
    badgeClass: 'bg-amber-600',
  },
  {
    id: 'cyan',
    name: 'Electric Cyan',
    primary: '#0891b2',
    hover: '#0e7490',
    active: '#155e75',
    lightBg: 'rgba(8, 145, 178, 0.12)',
    ring: '#22d3ee',
    badgeClass: 'bg-cyan-600',
  },
  {
    id: 'purple',
    name: 'Imperial Purple',
    primary: '#9333ea',
    hover: '#7e22ce',
    active: '#6b21a8',
    lightBg: 'rgba(147, 51, 234, 0.12)',
    ring: '#c084fc',
    badgeClass: 'bg-purple-600',
  },
  {
    id: 'teal',
    name: 'Nordic Teal',
    primary: '#0d9488',
    hover: '#0f766e',
    active: '#115e59',
    lightBg: 'rgba(13, 148, 136, 0.12)',
    ring: '#2dd4bf',
    badgeClass: 'bg-teal-600',
  },
  {
    id: 'slate',
    name: 'Obsidian Slate',
    primary: '#475569',
    hover: '#334155',
    active: '#1e293b',
    lightBg: 'rgba(71, 85, 105, 0.12)',
    ring: '#94a3b8',
    badgeClass: 'bg-slate-600',
  },
];

export const THEME_FONTS: FontFamilyOption[] = [
  {
    id: 'Inter',
    name: 'Inter',
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    description: 'Modern, balanced, highly legible enterprise standard',
    sample: 'Ag PeopleOS 2026',
  },
  {
    id: 'Plus Jakarta Sans',
    name: 'Plus Jakarta Sans',
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    description: 'Clean, contemporary, friendly geometric aesthetics',
    sample: 'Ag PeopleOS 2026',
  },
  {
    id: 'Outfit',
    name: 'Outfit',
    fontFamily: "'Outfit', sans-serif",
    description: 'Sleek geometric display, elevated tech brand identity',
    sample: 'Ag PeopleOS 2026',
  },
  {
    id: 'Roboto',
    name: 'Roboto',
    fontFamily: "'Roboto', sans-serif",
    description: 'Classic, dual-nature mechanical skeleton and friendly curves',
    sample: 'Ag PeopleOS 2026',
  },
  {
    id: 'Poppins',
    name: 'Poppins',
    fontFamily: "'Poppins', sans-serif",
    description: 'Soft geometric curves, modern international warmth',
    sample: 'Ag PeopleOS 2026',
  },
];

export const DEFAULT_CUSTOMIZER_SETTINGS: CustomizerSettings = {
  color: 'violet',
  font: 'Inter',
  darkSidebar: false,
  darkNavbar: false,
  mode: 'system',
  radius: 'standard',
  density: 'comfortable',
};
