import mongoose from 'mongoose';
import * as dotenv from 'dotenv';
import { generateUuid } from '../common/utils/uuid.util';

dotenv.config({ path: ['.env', '../.env'] });

const MONGODB_URI =
  process.env.MONGODB_URI || 'mongodb://localhost:27017/peopleos';

async function seedLocationsAndDesignations() {
  console.log('Connecting to MongoDB at:', MONGODB_URI);
  await mongoose.connect(MONGODB_URI);

  const db = mongoose.connection.db;
  if (!db) throw new Error('Database connection not established');

  const orgsCollection = db.collection<any>('organizations');
  const locsCollection = db.collection<any>('locations');
  const desigsCollection = db.collection<any>('designations');

  // Find or create default organization
  const org = await orgsCollection.findOne({ isDeleted: false });
  if (!org) {
    throw new Error('No organization found. Please run seed-departments first.');
  }
  const orgId = String(org._id);

  // Clear existing locations and designations for clean re-seeding
  await locsCollection.deleteMany({ organizationId: orgId });
  await desigsCollection.deleteMany({ organizationId: orgId });
  console.log('Cleared existing locations and designations for org:', org.legalName);

  // -------------------------------------------------------------
  // 1. 12 INDIAN TECH HUB OFFICE LOCATIONS
  // -------------------------------------------------------------
  const locationsData = [
    {
      _id: generateUuid(),
      organizationId: orgId,
      name: 'Bangalore Manyata HQ',
      address: 'Manyata Embassy Business Park, Outer Ring Road',
      addressLine2: 'Block G3, 5th Floor, Nagavara',
      city: 'Bengaluru',
      state: 'Karnataka',
      country: 'India',
      postalCode: '560045',
      timezone: 'Asia/Kolkata',
      latitude: 13.0498,
      longitude: 77.6202,
      employeeCount: 0,
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      name: 'Hyderabad HITEC City Center',
      address: 'Cyber Towers, HITEC City, Madhapur',
      addressLine2: 'Quadrant 4, 8th Floor',
      city: 'Hyderabad',
      state: 'Telangana',
      country: 'India',
      postalCode: '500081',
      timezone: 'Asia/Kolkata',
      latitude: 17.4504,
      longitude: 78.3808,
      employeeCount: 0,
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      name: 'Chennai TIDEL Park Campus',
      address: 'TIDEL Park, Rajiv Gandhi Salai (OMR), Taramani',
      addressLine2: 'Module 602, 6th Floor',
      city: 'Chennai',
      state: 'Tamil Nadu',
      country: 'India',
      postalCode: '600113',
      timezone: 'Asia/Kolkata',
      latitude: 12.9893,
      longitude: 80.2483,
      employeeCount: 0,
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      name: 'Pune Hinjawadi Tech Park',
      address: 'Rajiv Gandhi Infotech Park, Hinjawadi Phase 1',
      addressLine2: 'SEZ Tower 2, 4th Floor',
      city: 'Pune',
      state: 'Maharashtra',
      country: 'India',
      postalCode: '411057',
      timezone: 'Asia/Kolkata',
      latitude: 18.5913,
      longitude: 73.7389,
      employeeCount: 0,
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      name: 'Mumbai Airoli Mindspace',
      address: 'Mindspace Airoli West, Thane-Belapur Road',
      addressLine2: 'Building 9, 3rd Floor',
      city: 'Navi Mumbai',
      state: 'Maharashtra',
      country: 'India',
      postalCode: '400708',
      timezone: 'Asia/Kolkata',
      latitude: 19.1678,
      longitude: 72.9976,
      employeeCount: 0,
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      name: 'Gurugram Cyber City Hub',
      address: 'DLF Cyber City, Phase 2',
      addressLine2: 'Building 10, Tower B, 11th Floor',
      city: 'Gurugram',
      state: 'Haryana',
      country: 'India',
      postalCode: '122002',
      timezone: 'Asia/Kolkata',
      latitude: 28.4952,
      longitude: 77.0894,
      employeeCount: 0,
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      name: 'Noida Expressway Tech Park',
      address: 'Advant Navis Business Park, Sector 142',
      addressLine2: 'Tower A, 9th Floor',
      city: 'Noida',
      state: 'Uttar Pradesh',
      country: 'India',
      postalCode: '201305',
      timezone: 'Asia/Kolkata',
      latitude: 28.5034,
      longitude: 77.4124,
      employeeCount: 0,
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      name: 'Kochi Infopark Phase 2',
      address: 'Infopark SEZ, Kakkanad',
      addressLine2: 'Jyothirmaya Building, 4th Floor',
      city: 'Kochi',
      state: 'Kerala',
      country: 'India',
      postalCode: '682042',
      timezone: 'Asia/Kolkata',
      latitude: 10.0124,
      longitude: 76.3664,
      employeeCount: 0,
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      name: 'Coimbatore TIDEL Park',
      address: 'TIDEL Park, Civil Aerodrome Post, Peelamedu',
      addressLine2: 'ELCOT SEZ, Module 301, 3rd Floor',
      city: 'Coimbatore',
      state: 'Tamil Nadu',
      country: 'India',
      postalCode: '641014',
      timezone: 'Asia/Kolkata',
      latitude: 11.0286,
      longitude: 77.0278,
      employeeCount: 0,
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      name: 'GIFT City FinTech Center',
      address: 'Gujarat International Finance Tec-City, Zone 1',
      addressLine2: 'GIFT One Tower, 14th Floor',
      city: 'Gandhinagar',
      state: 'Gujarat',
      country: 'India',
      postalCode: '382355',
      timezone: 'Asia/Kolkata',
      latitude: 23.1611,
      longitude: 72.6841,
      employeeCount: 0,
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      name: 'Kolkata Salt Lake Sector V',
      address: 'Salt Lake City, Sector V, Bidhannagar',
      addressLine2: 'Infinity Benchmark, 12th Floor',
      city: 'Kolkata',
      state: 'West Bengal',
      country: 'India',
      postalCode: '700091',
      timezone: 'Asia/Kolkata',
      latitude: 22.5804,
      longitude: 88.4312,
      employeeCount: 0,
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      name: 'Trivandrum Technopark Phase 3',
      address: 'Technopark Campus, Karyavattom',
      addressLine2: 'Ganga Building, 2nd Floor',
      city: 'Thiruvananthapuram',
      state: 'Kerala',
      country: 'India',
      postalCode: '695581',
      timezone: 'Asia/Kolkata',
      latitude: 8.5566,
      longitude: 76.8821,
      employeeCount: 0,
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];

  await locsCollection.insertMany(locationsData);
  console.log('✅ Seeded 12 Indian tech hub office locations.');

  // -------------------------------------------------------------
  // 2. 20 JOB DESIGNATIONS (Span Grade 1 to 10 - Junior to C-Suite)
  // -------------------------------------------------------------
  const designationsData = [
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'Managing Director (MD)',
      code: 'MD',
      grade: 10,
      assignedEmployeeCount: 0,
      description: 'Executive leadership directing corporate strategy, fiduciary operations, and board governance.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'Chief Technology Officer (CTO)',
      code: 'CTO',
      grade: 10,
      assignedEmployeeCount: 0,
      description: 'Executive technology officer leading architectural roadmaps, core R&D innovations, and tech stack governance.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'Vice President (VP)',
      code: 'VP',
      grade: 9,
      assignedEmployeeCount: 0,
      description: 'Executive operational leader overseeing cross-functional technology divisions, delivery management, and organizational scale.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'Assistant Vice President - Sales (AVP Sales)',
      code: 'AVP-SALES',
      grade: 9,
      assignedEmployeeCount: 0,
      description: 'Executive sales leader driving strategic client acquisition, enterprise solution contracts, and revenue targets.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'Director',
      code: 'DIR',
      grade: 8,
      assignedEmployeeCount: 0,
      description: 'Departmental director supervising operations, budget allocations, resource planning, and multi-team programs.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'Director of Software Engineering',
      code: 'DSE',
      grade: 8,
      assignedEmployeeCount: 0,
      description: 'Directs the software engineering division, engineering best practices, technical roadmaps, and delivery velocity across multiple squads.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'Associate Director',
      code: 'ADIR',
      grade: 8,
      assignedEmployeeCount: 0,
      description: 'Senior departmental leader assisting in organizational governance, high-level client management, and program scale.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'Principal Engineer',
      code: 'PE',
      grade: 7,
      assignedEmployeeCount: 0,
      description: 'Staff technical authority architecting high-scale distributed systems, fault-tolerant infrastructure, and microservices standards.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'Project Manager',
      code: 'PM',
      grade: 7,
      assignedEmployeeCount: 0,
      description: 'End-to-end agile project delivery, sprint coordination, resource scheduling, client communications, and milestone tracking.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'Team Lead',
      code: 'TL',
      grade: 7,
      assignedEmployeeCount: 0,
      description: 'Technical squad lead conducting sprint planning, PR code reviews, architectural adherence, and developer mentorship.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'QA Engineer Lead',
      code: 'QAL',
      grade: 7,
      assignedEmployeeCount: 0,
      description: 'Quality assurance lead designing automated test frameworks, regression suites, CI/CD quality gates, and release signoffs.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'Senior Developer',
      code: 'SR-DEV',
      grade: 6,
      assignedEmployeeCount: 0,
      description: 'Senior software engineer designing scalable backend microservices, resilient APIs, and complex frontend architectures.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'AI / ML Engineer',
      code: 'AIML-ENG',
      grade: 6,
      assignedEmployeeCount: 0,
      description: 'Specialist engineer in machine learning pipelines, LLM fine-tuning, neural networks, vector databases, and AI model serving.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'Full Stack Developer',
      code: 'FSD',
      grade: 5,
      assignedEmployeeCount: 0,
      description: 'Engineers responsive user interfaces and backend server logic using modern React, Node.js, and database ecosystems.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'Cloud DevOps Engineer',
      code: 'DEVOPS',
      grade: 5,
      assignedEmployeeCount: 0,
      description: 'Builds and maintains Kubernetes clusters, Terraform infrastructure-as-code, and automated CI/CD deployment pipelines.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'Business Analyst',
      code: 'BA',
      grade: 5,
      assignedEmployeeCount: 0,
      description: 'Analyzes business requirements, crafts user stories, and collaborates between IT stakeholders and technical squads.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'QA Engineer',
      code: 'QA-ENG',
      grade: 4,
      assignedEmployeeCount: 0,
      description: 'Performs manual, automated, integration, and API testing to ensure reliable, defect-free software releases.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'UI / UX Designer',
      code: 'UIUX-DES',
      grade: 4,
      assignedEmployeeCount: 0,
      description: 'Designs design systems, wireframes, user personas, high-fidelity prototypes, and design-to-development handoffs in Figma.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'Sales and Marketing Specialist',
      code: 'SALES-MKT',
      grade: 4,
      assignedEmployeeCount: 0,
      description: 'Executes IT marketing campaigns, business lead generation, digital outreach, and enterprise client relations.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'Junior Developer',
      code: 'JR-DEV',
      grade: 3,
      assignedEmployeeCount: 0,
      description: 'Associate developer contributing to feature implementations, unit testing, bug fixes, and continuous technical learning.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];

  await desigsCollection.insertMany(designationsData);
  console.log('✅ Seeded 20 corporate job designations (Grade 1 to 10).');

  console.log('----------------------------------------------------');
  console.log(`✅ Successfully seeded 15 Locations and 20 Designations for [${org.legalName}]`);
  console.log('----------------------------------------------------');

  await mongoose.disconnect();
}

seedLocationsAndDesignations().catch((err) => {
  console.error('❌ Error seeding locations/designations:', err);
  process.exit(1);
});
