import mongoose from 'mongoose';
import * as dotenv from 'dotenv';
import { generateUuid } from '../common/utils/uuid.util';

dotenv.config({ path: ['.env', '../.env'] });

const MONGODB_URI =
  process.env.MONGODB_URI || 'mongodb://localhost:27017/peopleos';

async function seedLocationsAndDesignations() {
  console.log('Connecting to MongoDB at:', MONGODB_URI);
  await mongoose.connect(MONGODB_URI);

  const db = mongoose.connection.db;
  if (!db) throw new Error('Database connection not established');

  const orgsCollection = db.collection<any>('organizations');
  const locsCollection = db.collection<any>('locations');
  const desigsCollection = db.collection<any>('designations');

  // Find or create default organization
  const org = await orgsCollection.findOne({ isDeleted: false });
  if (!org) {
    throw new Error('No organization found. Please run seed-departments first.');
  }
  const orgId = String(org._id);

  // Clear existing locations and designations for clean re-seeding
  await locsCollection.deleteMany({ organizationId: orgId });
  await desigsCollection.deleteMany({ organizationId: orgId });
  console.log('Cleared existing locations and designations for org:', org.legalName);

  // -------------------------------------------------------------
  // 1. 15 GLOBAL OFFICE LOCATIONS (Tech Hubs & Corporate Sites)
  // -------------------------------------------------------------
  const locationsData = [
    {
      _id: generateUuid(),
      organizationId: orgId,
      name: 'Global Headquarters (San Francisco)',
      address: '500 Howard Street, Suite 400',
      addressLine2: 'SoMa Tech Center',
      city: 'San Francisco',
      state: 'California',
      country: 'United States',
      postalCode: '94105',
      timezone: 'America/Los_Angeles',
      latitude: 37.7891,
      longitude: -122.3972,
      employeeCount: 145,
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      name: 'Bangalore Tech Center',
      address: 'Prestige Tech Park, Outer Ring Road',
      addressLine2: 'Block B, 6th Floor, Kadubeesanahalli',
      city: 'Bengaluru',
      state: 'Karnataka',
      country: 'India',
      postalCode: '560103',
      timezone: 'Asia/Kolkata',
      latitude: 12.9352,
      longitude: 77.6946,
      employeeCount: 220,
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      name: 'London European Headquarters',
      address: '100 Bishopsgate',
      addressLine2: 'Level 18, City of London',
      city: 'London',
      state: 'Greater London',
      country: 'United Kingdom',
      postalCode: 'EC2N 4AG',
      timezone: 'Europe/London',
      latitude: 51.5154,
      longitude: -0.0825,
      employeeCount: 68,
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      name: 'Singapore APAC Regional Hub',
      address: '1 Marina Boulevard',
      addressLine2: 'One Marina Boulevard #28-00',
      city: 'Singapore',
      state: 'Central Region',
      country: 'Singapore',
      postalCode: '018989',
      timezone: 'Asia/Singapore',
      latitude: 1.2823,
      longitude: 103.8525,
      employeeCount: 52,
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      name: 'New York Financial District Office',
      address: '1 World Trade Center',
      addressLine2: 'Floor 64',
      city: 'New York',
      state: 'New York',
      country: 'United States',
      postalCode: '10007',
      timezone: 'America/New_York',
      latitude: 40.7127,
      longitude: -74.0134,
      employeeCount: 42,
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      name: 'Berlin Engineering & Innovation Lab',
      address: 'Potsdamer Platz 10',
      addressLine2: 'Building 4, 3rd Floor',
      city: 'Berlin',
      state: 'Berlin',
      country: 'Germany',
      postalCode: '10785',
      timezone: 'Europe/Berlin',
      latitude: 52.5096,
      longitude: 13.3759,
      employeeCount: 38,
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      name: 'Hyderabad Software Campus',
      address: 'HITEC City, Madhapur',
      addressLine2: 'Cyber Gateway, Phase II',
      city: 'Hyderabad',
      state: 'Telangana',
      country: 'India',
      postalCode: '500081',
      timezone: 'Asia/Kolkata',
      latitude: 17.4435,
      longitude: 78.3772,
      employeeCount: 160,
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      name: 'Toronto Canada Hub',
      address: '181 Bay Street, Brookfield Place',
      addressLine2: 'Suite 2200',
      city: 'Toronto',
      state: 'Ontario',
      country: 'Canada',
      postalCode: 'M5J 2T3',
      timezone: 'America/New_York',
      latitude: 43.6473,
      longitude: -79.379,
      employeeCount: 35,
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      name: 'Sydney Australia Branch',
      address: '200 George Street',
      addressLine2: 'Level 24, Mirvac Tower',
      city: 'Sydney',
      state: 'New South Wales',
      country: 'Australia',
      postalCode: 'NSW 2000',
      timezone: 'Australia/Sydney',
      latitude: -33.8634,
      longitude: 151.2087,
      employeeCount: 28,
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      name: 'Dubai DIFC Commercial Hub',
      address: 'Gate Precinct 4, DIFC',
      addressLine2: 'Office 502, Level 5',
      city: 'Dubai',
      state: 'Dubai',
      country: 'United Arab Emirates',
      postalCode: 'PO Box 506500',
      timezone: 'Asia/Dubai',
      latitude: 25.2104,
      longitude: 55.2818,
      employeeCount: 22,
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      name: 'Tokyo Japan Office',
      address: 'Roppongi Hills Mori Tower',
      addressLine2: '6-10-1 Roppongi, 29th Floor',
      city: 'Minato-ku, Tokyo',
      state: 'Tokyo',
      country: 'Japan',
      postalCode: '106-6129',
      timezone: 'Asia/Tokyo',
      latitude: 35.6605,
      longitude: 139.7292,
      employeeCount: 18,
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      name: 'Austin Texas Tech Center',
      address: '500 W 2nd St',
      addressLine2: 'Suite 1900',
      city: 'Austin',
      state: 'Texas',
      country: 'United States',
      postalCode: '78701',
      timezone: 'America/Chicago',
      latitude: 30.2657,
      longitude: -97.7479,
      employeeCount: 45,
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      name: 'Pune IT Park',
      address: 'Rajiv Gandhi Infotech Park, Hinjawadi',
      addressLine2: 'Phase 1, SEZ Tower 3',
      city: 'Pune',
      state: 'Maharashtra',
      country: 'India',
      postalCode: '411057',
      timezone: 'Asia/Kolkata',
      latitude: 18.5913,
      longitude: 73.7389,
      employeeCount: 88,
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      name: 'Paris Operations Center',
      address: '32 Boulevard Haussmann',
      addressLine2: '9th Arrondissement',
      city: 'Paris',
      state: 'Île-de-France',
      country: 'France',
      postalCode: '75009',
      timezone: 'Europe/Paris',
      latitude: 48.8732,
      longitude: 2.3364,
      employeeCount: 16,
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      name: 'Chicago Regional Sales Office',
      address: '233 S Wacker Dr, Willis Tower',
      addressLine2: 'Suite 4500',
      city: 'Chicago',
      state: 'Illinois',
      country: 'United States',
      postalCode: '60606',
      timezone: 'America/Chicago',
      latitude: 41.8789,
      longitude: -87.6359,
      employeeCount: 24,
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];

  await locsCollection.insertMany(locationsData);
  console.log('✅ Seeded 15 international office locations.');

  // -------------------------------------------------------------
  // 2. 20 JOB DESIGNATIONS (Span Grade 1 to 10 - Junior to C-Suite)
  // -------------------------------------------------------------
  const designationsData = [
    // Junior / Associate Track (Grade 1 - 3)
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'Graduate Engineering Trainee',
      code: 'DES-GET-01',
      grade: 1,
      assignedEmployeeCount: 18,
      description: 'Entry-level trainee rotation across software development, QA, and infrastructure.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'Associate Software Engineer',
      code: 'DES-ASE-02',
      grade: 2,
      assignedEmployeeCount: 32,
      description: 'Junior developer writing core modules, test fixtures, and minor bug resolutions.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'Associate QA Analyst',
      code: 'DES-AQA-03',
      grade: 2,
      assignedEmployeeCount: 14,
      description: 'Manual and regression test execution, test case documentation, and issue reporting.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'Associate People Ops Specialist',
      code: 'DES-APO-04',
      grade: 3,
      assignedEmployeeCount: 8,
      description: 'HR documentation, employee onboarding logistics, and attendance tracking.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },

    // Mid-Level Professional Track (Grade 4 - 6)
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'Software Engineer II',
      code: 'DES-SE2-05',
      grade: 4,
      assignedEmployeeCount: 48,
      description: 'Independent feature engineering, API integrations, and code reviews.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'UI/UX Designer',
      code: 'DES-UID-06',
      grade: 4,
      assignedEmployeeCount: 12,
      description: 'Wireframing, interactive prototyping, user journey mapping, and Figma tokens.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'Cloud DevOps Engineer',
      code: 'DES-OPS-07',
      grade: 5,
      assignedEmployeeCount: 16,
      description: 'CI/CD pipeline maintenance, Terraform cloud provisioning, and container deployment.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'Senior Software Engineer',
      code: 'DES-SSE-08',
      grade: 6,
      assignedEmployeeCount: 54,
      description: 'High-throughput system design, architectural standards, and junior mentorship.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'Senior Product Manager',
      code: 'DES-SPM-09',
      grade: 6,
      assignedEmployeeCount: 10,
      description: 'Product lifecycle ownership, customer discovery, sprint prioritization, and KPI tracking.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'Senior Financial Analyst',
      code: 'DES-SFA-10',
      grade: 6,
      assignedEmployeeCount: 7,
      description: 'Corporate financial forecasting, budget variances, and monthly ledger reconciliations.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },

    // Senior & Lead Track (Grade 7 - 8)
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'Lead Software Architect',
      code: 'DES-LSA-11',
      grade: 7,
      assignedEmployeeCount: 8,
      description: 'Enterprise technical vision, microservices roadmap, and fault-tolerant cloud design.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'Engineering Manager',
      code: 'DES-EMG-12',
      grade: 7,
      assignedEmployeeCount: 14,
      description: 'Engineering squad leadership, delivery velocity, 1-on-1s, and career progression.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'Lead Security Engineer',
      code: 'DES-LSE-13',
      grade: 7,
      assignedEmployeeCount: 5,
      description: 'SOC2/ISO compliance enforcement, penetration testing, and zero-trust IAM policies.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'Talent Acquisition Manager',
      code: 'DES-TAM-14',
      grade: 7,
      assignedEmployeeCount: 6,
      description: 'Leadership recruitment strategy, recruitment marketing, and agency management.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'Director of Engineering',
      code: 'DES-DOE-15',
      grade: 8,
      assignedEmployeeCount: 5,
      description: 'Cross-functional engineering organization head overseeing multiple squads and budgets.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'Director of Human Resources',
      code: 'DES-DHR-16',
      grade: 8,
      assignedEmployeeCount: 3,
      description: 'Global workforce strategy, compensation band design, and organizational culture.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },

    // Executive & C-Suite Leadership (Grade 9 - 10)
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'Vice President of Engineering',
      code: 'DES-VPE-17',
      grade: 9,
      assignedEmployeeCount: 2,
      description: 'Overall technical execution, technology governance, and multi-region engineering scaling.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'Vice President of Global Sales',
      code: 'DES-VPS-18',
      grade: 9,
      assignedEmployeeCount: 2,
      description: 'Worldwide revenue quotas, channel partnerships, and global enterprise contracts.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'Chief Technology Officer (CTO)',
      code: 'DES-CTO-19',
      grade: 10,
      assignedEmployeeCount: 1,
      description: 'Executive technology officer, patents and IP, R&D innovations, and board advisement.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: generateUuid(),
      organizationId: orgId,
      title: 'Chief Executive Officer (CEO)',
      code: 'DES-CEO-20',
      grade: 10,
      assignedEmployeeCount: 1,
      description: 'Chief Executive Officer leading corporate vision, investor relations, and board governance.',
      status: 'ACTIVE',
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];

  await desigsCollection.insertMany(designationsData);
  console.log('✅ Seeded 20 corporate job designations (Grade 1 to 10).');

  console.log('----------------------------------------------------');
  console.log(`✅ Successfully seeded 15 Locations and 20 Designations for [${org.legalName}]`);
  console.log('----------------------------------------------------');

  await mongoose.disconnect();
}

seedLocationsAndDesignations().catch((err) => {
  console.error('❌ Error seeding locations/designations:', err);
  process.exit(1);
});
